openapi: 3.0.1
info:
  title: Dave Sag's Boilerplate API
  description: A boilerplate API codebase
  contact:
    email: 'davesag@gmail.com'
  license:
    name: 'MIT License'
    url: https://opensource.org/licenses/MIT
  version: 1.0.0
servers:
- url: /api/v1
tags:
- name: root
  description: Root level API paths
- name: v1
  description: Version 1 API Paths
paths:
  /:
    get:
      tags:
      - root
      servers:
      - url: /
      summary: Display API version information
      operationId: versions
      responses:
        200:
          description: Information about the available API Versions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VersionResponse'
  /ping:
    get:
      tags:
      - root
      servers:
      - url: /
      summary: Checks that the server is alive
      operationId: ping
      responses:
        200:
          description: 'Information about the server'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PingResponse'
  /hello/{name}:
    get:
      tags:
      - v1
      summary: Say hello to the name provided
      operationId: v1/hello
      parameters:
        - in: path
          name: name
          description: 'The name to say hello to'
          schema:
            type: string
          required: true
      responses:
        200:
          description: 'Just says hello'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelloWorldResponse'
        400:
          description: 'Bad request —Invalid name supplied'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /snooze:
    get:
      tags:
      - v1
      summary: Just wait a bit
      operationId: v1/snooze
      responses:
        200:
          description: 'Okay'
components:
  schemas:
    PingResponse:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        version:
          type: string
        uptime:
          type: number
    APIVersion:
      type: object
      properties:
        version:
          type: integer
          description: The API's version number
        path:
          type: string
          description: The relative path to the API
    VersionResponse:
      type: array
      items:
        $ref: '#/components/schemas/APIVersion'
    HelloWorldResponse:
      type: string
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: The error message
